### ISSUE TITLE
Cant download python module on windows

### ISSUE THREAD

**Issue by kwurster** [HPE-Haven-OnDemand/havenondemand-python#1]
i am using python 3.5 on a windows 7.1 box and get the following error when trying to install the python  module from git

C:\Python\Python35-32\Scripts>pip install git+https://github.com/lemoogle/iod-py
thon
Collecting git+https://github.com/lemoogle/iod-python
  Cloning https://github.com/lemoogle/iod-python to c:\users\kkkkk\appdata\lo
cal\temp\pip-87u_vcto-build
  Error [WinError 2] The system cannot find the file specified while executing c
ommand git clone -q https://github.com/lemoogle/iod-python C:\Users\kkkk\App
Data\Local\Temp\pip-87u_vcto-build
Cannot find command 'git'

**Comment by tylernappy** [comment]
Try using the following command instead:

`pip install git+https://github.com/HP-Haven-OnDemand/iod-python`

**Comment by lemoogle** [comment]
YOu should use the link tyler provided rather than the "lemoogle" one , but I believe the install is failing because git is not installed. Install git and make sure that you tick the option which adds it to the bash command line.

**Comment by kwurster** [comment]
installed git and tried again and got the following error:

C:\Python\Python35-32>pip install git+https://github.com/HP-Haven-OnDemand/iod-p
ython
Collecting git+https://github.com/HP-Haven-OnDemand/iod-python
  Cloning https://github.com/HP-Haven-OnDemand/iod-python to c:\users\kwurster\a
ppdata\local\temp\pip-2qrb8mx6-build
fatal: unable to access 'https://github.com/HP-Haven-OnDemand/iod-python/': Fail
ed to connect to github.com port 443: Timed out
  Complete output from command git clone -q https://github.com/HP-Haven-OnDemand
/iod-python C:\Users\kwurster\AppData\Local\Temp\pip-2qrb8mx6-build:

  ----------------------------------------
Command "git clone -q https://github.com/HP-Haven-OnDemand/iod-python C:\Users\k
wurster\AppData\Local\Temp\pip-2qrb8mx6-build" failed with error code 128 in Non
e

C:\Python\Python35-32>

**Comment by kwurster** [comment]
Installed git but getting the following error now:

C:\Python\Python35-32>pip install git+https://github.com/HP-Haven-OnDemand/iod-p
ython
Collecting git+https://github.com/HP-Haven-OnDemand/iod-python
  Cloning https://github.com/HP-Haven-OnDemand/iod-python to c:\users\kwurster\a
ppdata\local\temp\pip-9fvhmhkx-build
fatal: unable to access 'https://github.com/HP-Haven-OnDemand/iod-python/': Fail
ed to connect to github.com port 443: Timed out
  Complete output from command git clone -q https://github.com/HP-Haven-OnDemand
/iod-python C:\Users\kwurster\AppData\Local\Temp\pip-9fvhmhkx-build:

  ----------------------------------------
Command "git clone -q https://github.com/HP-Haven-OnDemand/iod-python C:\Users\k
wurster\AppData\Local\Temp\pip-9fvhmhkx-build" failed with error code 128 in Non
e

C:\Python\Python35-32>

Any ideas?

Klaus

**Comment by lemoogle** [comment]
Sounds like it's a proxy setting

Set your HTTPS_PROXY environment variable before running it.

**Comment by kwurster** [comment]
Hi Martin,

That worked.
Tyler, maybe it would be a good idea to add these two steps (locally installing git and setting HTTPS_PROXY) to the install instructions?

Klaus
